name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Run build
        run: go build -ldflags="-s -w"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: poligo
          path: |
            poligo

